
name: Gradle Build on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      
      - name: Grant gradlew execute permission
        run: icacls gradlew /grant Everyone:F
        
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Build with Gradle
        run: .\gradlew.bat build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jar-output
          path: build/libs/*.jar
          retention-days: 7
